<?xml version="1.0" encoding="UTF-8"?>
<!-- Completa el encabezado -->
<!DOCTYPE eurovision [
    <!ELEMENT eurovision (candidatura+)>
    <!ELEMENT candidatura (pais, titulo, artista, idioma+, video)>
    <!ELEMENT pais (#PCDATA)>
    <!ELEMENT titulo (original, castellano)>
    <!ELEMENT original (#PCDATA)>
    <!ELEMENT castellano (#PCDATA)>
    <!ELEMENT artista (#PCDATA)>
    <!ELEMENT idioma (#PCDATA)>
    <!ELEMENT video (#PCDATA)>
]>
<eurovision> 
	<candidatura>
		<!-- Cada una de las filas de la tabla sera una candidatura. Continua desde aqui -->
    <pais>Alemania</pais>
    <titulo>
      <original>Roxkstars</original>
      <castellano>Estrellas del rock</castellano>    
    </titulo>
    <artista>Malik Harris</artista>
    <idioma>Inglés</idioma>
    <video>D3FN2umFaM8</video>
</candidatura>
  <candidatura>
    <pais>España</pais>
    <titulo>
      <original>SloMo</original>
      <castellano>Cámara lenta</castellano>    
    </titulo>  
    <artista>Chanel</artista>
    <idioma>Español</idioma>
    <idioma>Inglés</idioma>
    <video>TO2yGXVQCfo</video>
  </candidatura>
  <candidatura>
    <pais>Finlandia</pais> 
    <titulo>
      <original>Jezebel</original>
      <castellano>Jezebel</castellano>    
    </titulo> 
    <artista>The Rasmus</artista>
    <idioma>Inglés</idioma>
    <video>XtMfCf3vFbc</video>
  </candidatura>
  <candidatura>
    <pais>Italia</pais>
    <titulo>
      <original>Brividi</original>
      <castellano>Escalofríos</castellano>    
    </titulo>  
    <artista> Mahmood &amp; Blanco</artista>
    <idioma>Italiano</idioma>
    <video>4MgMhzfUmiA</video>
  </candidatura>
  <candidatura>
    <pais>Ucrania</pais>
    <titulo>
      <original>Stefania</original>
      <castellano>Estefanía</castellano>    
    </titulo>  
    <artista>Kalush Orchstra</artista>
    <idioma>Ucraniano</idioma>
    <video>UiEGVYOruLk</video>
  </candidatura>
</eurovision>